apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering-deployment
  namespace: "2401048"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-ordering
  template:
    metadata:
      labels:
        app: food-ordering
    spec:
      imagePullSecrets:
        -name: nexus-secret 
      containers:
        - name: food-ordering
          image: 120.0.0.1:30085/2401048/food-ordering:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: food-ordering-service
  namespace: "2401048"
spec:
  type: NodePort
  selector:
    app: food-ordering
  ports:
    - protocol: TCP
      port: 80 # Internal cluster port
      targetPort: 80 # Pod container port
      nodePort: 31086 # Host accessible port (FREE PORT)