apiVersion: v1
kind: Service
metadata:
  name: food-ordering-service
  namespace: "2401048"
spec:
  type: NodePort
  selector:
    app: food-ordering
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 80    # containerPort in pod
      nodePort: 31086   # NodePort exposed on the node